site_name: "Basic Formal Ontology"
repo_url: https://github.com/johnbeve/hub-and-spoke/
edit_uri: '?query=root/hub-and-spoke/docs/'
theme:
  name: readthedocs
docs_dir: docs
nav:
  - Home: index.md
  - Preface: preface.md
  - Introduction: introduction.md
  - Basic Formal Ontology: basic-formal-ontology.md
  - Scope: scope.md
  - Conformance: conformance.md
  - Users and Applications: users-and-applications.md
  - Terms and Definitions: terms-and-definitions.md
  - Conventions: conventions.md
  - BFO-Core: bfo-core.md
  - Temporal Extensions: temporal-extensions.md
  - Important Extensions: important-extensions.md
  - Summary: summary.md




