site_name: "Basic Formal Ontology"
repo_url: https://github.com/johnbeve/hub-and-spoke/
edit_uri: '?query=root/hub-and-spoke/docs/'
theme:
  name: material
  features:
    - header.autohide
  palette:
    primary: 'white'
    accent: 'green'
    scheme: 'slate'
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Scope: scope.md
  - Conformance: conformance.md
  - Conventions: conventions.md
  - Terms and Definitions: terms-and-definitions.md
  - BFO-Core: bfo-core.md
  - Temporal Extensions: temporal-extensions.md
  - Users and Applications: users-and-applications.md
  - Summary: summary.md



