site_name: "Basic Formal Ontology"
repo_url: https://github.com/johnbeve/hub-and-spoke/
edit_uri: '?query=root/hub-and-spoke/docs/'
theme:
  name: readthedocs
nav:
  - Home: docs/index.md
  - Preface: docs/preface.md
  - Introduction: docs/introduction.md
  - Basic Formal Ontology: docs/basic-formal-ontology.md
  - Scope: docs/scope.md
  - Conformance: docs/conformance.md
  - Users and Applications: docs/users-and-applications.md
  - Terms and Definitions: docs/terms-and-definitions.md
  - Conventions: docs/conventions.md
  - BFO-Core: docs/bfo-core.md
  - Temporal Extensions: docs/temporal-extensions.md
  - Important Extensions: docs/important-extensions.md
  - Summary: docs/summary.md




